name: Mirror to GitLab

on:
  push:
    branches:
      - main  # or the branch you want to mirror

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key for GitLab
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}

    - name: Add GitLab to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

    - name: Mirror to GitLab
      run: |
        git remote add gitlab ${{ secrets.GITLAB_URL }}
        git push --mirror gitlab
