name: Sync GitHub to GitLab

on:
  push:
    branches:
      - main  # or any branch you want to trigger on

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git for GitLab
        run: |
          git config --global url."https://${{ secrets.GITLAB_TOKEN }}:x-oauth-basic@gitlab.com/".insteadOf "https://gitlab.com/"
          git remote add gitlab https://gitlab.com/getachewgetu/github-gitlab-pipline-setup.git
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

      - name: Push to GitLab
        run: |
          git push --mirror gitlab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
