name: Mirror to GitLab

on:
  push:
    branches:
      - main  # Adjust this to your primary branch if different

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git to use GitLab token for authentication
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        # Configure Git to use GitLab token for authentication
        git config --global url."https://${GITLAB_TOKEN}:x-oauth-basic@gitlab.com/".insteadOf "https://gitlab.com/"
        
    - name: Add GitLab repository as a remote
      env:
        GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
      run: |
        # Add GitLab repository as a remote
        git remote add gitlab $GITLAB_REPO_URL
        
    - name: Push all branches and tags to GitLab
      run: |
        # Push all branches and tags to GitLab
        git push --mirror gitlab
